
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title


# Setup
timezone:            asia/hanoi # eg. Asia/Kathmandu
locale:              vi_VN # eg. en_us
name:				 Dung Tao (taomanhdung)
title:               taomanhdung
tagline:             'Software Developer - Tennis Lover'
description:         'Personal website of Dung Tao, Software Developer - Tennis Lover'
url:                 site url
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/images/td-logo.png' # [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Tao Manh Dung
  url:            	 taomanhdung.com
  facebook:          manhdung.niit
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           manhdung.niit
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "LICENSE","CNAME", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
